### PR TITLE
Add Chaela and Bi to the contributors page and update punctuation

### PR DESCRIPTION
**Pull request by dm36**
Updates contributors page and replaces exclamation marks with periods.

### CODE REVIEW

**Comment by dm36** [comment]
Images are looking a little shrunk (Javi and Chaela's) so trying to figure out how to fix the styling

**Comment by dm36** [comment]
Screen Shot 2021-10-03 at 5 14 57 PM

**Comment by dm36** [comment]
Screen Shot 2021-10-03 at 5 16 20 PM

**Comment by FizbanUXD** [comment]
Maybe zoom in and crop?

**Comment by kaisenl** [comment]
Yeah, just crop. It's easier to adjust the photo and keep the code consistent with everyone else's photo

**Comment by sei1122** [comment]
photos need to be a 1: 1 ratio.  
Let me know if you need to help crop the photos.

**Review by lewilliams89 — APPROVED** [review]

**Pull request merged**
